/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    users: User;
    students: Student;
    teachers: Teacher;
    classes: Class;
    schedules: Schedule;
    announcements: Announcement;
    gallery: Gallery;
    redirects: Redirect;
    search: Search;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    students: StudentsSelect<false> | StudentsSelect<true>;
    teachers: TeachersSelect<false> | TeachersSelect<true>;
    classes: ClassesSelect<false> | ClassesSelect<true>;
    schedules: SchedulesSelect<false> | SchedulesSelect<true>;
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    header: Header;
    footer: Footer;
    'school-settings': SchoolSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'school-settings': SchoolSettingsSelect<false> | SchoolSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    title: string;
    highImpactMedia?:
      | {
          image: number | Media;
          id?: string | null;
        }[]
      | null;
    mediumImpactMedia?: (number | null) | Media;
  };
  layout: (
    | AboutSection
    | SpecialitiesBlock
    | NewsCarousel
    | ContactAndFAQ
    | ContactBlock
    | GalleryBlock
    | ImageGalleryBlock
    | MapBlock
    | InfoRegisterBlock
    | TentangBlock
    | VideoGallery
    | VideoSectionBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutSection".
 */
export interface AboutSection {
  /**
   * Recommended size: 800x600px
   */
  leftImage: number | Media;
  /**
   * Optional subtitle text
   */
  subtitle?: string | null;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional button text (both text and link required for button to show)
   */
  buttonText?: string | null;
  /**
   * Optional button link (both text and link required for button to show)
   */
  buttonLink?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'aboutSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpecialitiesBlock".
 */
export interface SpecialitiesBlock {
  /**
   * Title for the specialities section
   */
  sectionTitle?: string | null;
  /**
   * Add speciality items to display in the grid
   */
  items: {
    /**
     * Choose an icon
     */
    icon:
      | 'fa-solid fa-certificate'
      | 'fa-solid fa-circle-check'
      | 'fa-solid fa-circle-user'
      | 'fas fa-earth-americas'
      | 'fa-solid fa-hand-holding-dollar'
      | 'fa-solid fa-person-chalkboard'
      | 'fa-solid fa-chalkboard-user'
      | 'fa-solid fa-clock';
    title: string;
    description: string;
    /**
     * Choose a background color
     */
    color: '#695ac7' | '#4582ff' | '#55b56a' | '#f27676' | '#35c5fa';
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'specialities';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsCarousel".
 */
export interface NewsCarousel {
  /**
   * Small section label, e.g., "Publikasi"
   */
  subtitle?: string | null;
  /**
   * Section heading, e.g., "News & Blog"
   */
  heading: string;
  /**
   * Maximum number of posts to show in the carousel
   */
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'newsCarousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactAndFAQ".
 */
export interface ContactAndFAQ {
  formSubtitle?: string | null;
  formTitle?: string | null;
  fullNameLabel?: string | null;
  phoneLabel?: string | null;
  emailLabel?: string | null;
  messageLabel?: string | null;
  submitLabel?: string | null;
  faqSubtitle?: string | null;
  faqTitle?: string | null;
  faqs?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactAndFAQ';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock".
 */
export interface ContactBlock {
  title: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  formTitle: string;
  showAddress?: boolean | null;
  showPhone?: boolean | null;
  showEmail?: boolean | null;
  address?: string | null;
  phoneNumber?: string | null;
  emailAddress?: string | null;
  formPlaceholders?: {
    name?: string | null;
    email?: string | null;
    message?: string | null;
    submit?: string | null;
  };
  socialMedia?:
    | {
        platform: 'facebook' | 'twitter' | 'instagram' | 'linkedin' | 'youtube' | 'tiktok' | 'github';
        url: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock".
 */
export interface GalleryBlock {
  subtitle?: string | null;
  title: string;
  items?:
    | {
        title: string;
        image: number | Media;
        description?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'galleryBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageGalleryBlock".
 */
export interface ImageGalleryBlock {
  images: {
    image: number | Media;
    title: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageGalleryBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MapBlock".
 */
export interface MapBlock {
  title?: string | null;
  latitude: number;
  longitude: number;
  zoom?: number | null;
  label?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mapBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InfoRegisterBlock".
 */
export interface InfoRegisterBlock {
  title?: string | null;
  buttonHref?: string | null;
  buttonLabel?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'infoRegisterBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TentangBlock".
 */
export interface TentangBlock {
  left?: {
    image?: (number | null) | Media;
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  right?: {
    widgets?:
      | {
          title: string;
          items?:
            | {
                label: string;
                link?: {
                  type?: ('reference' | 'custom') | null;
                  newTab?: boolean | null;
                  reference?:
                    | ({
                        relationTo: 'pages';
                        value: number | Page;
                      } | null)
                    | ({
                        relationTo: 'posts';
                        value: number | Post;
                      } | null);
                  staticPath?: ('' | '/posts') | null;
                  url?: string | null;
                };
                image: number | Media;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'tentangBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug?: string | null;
  slugLock?: boolean | null;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoGallery".
 */
export interface VideoGallery {
  videos: {
    /**
     * Enter the YouTube embed URL (e.g., https://www.youtube.com/embed/VIDEO_ID)
     */
    youtubeUrl: string;
    /**
     * Enter a title for this video
     */
    title: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'video-gallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoSectionBlock".
 */
export interface VideoSectionBlock {
  /**
   * Upload a thumbnail image for the video
   */
  thumbnail: number | Media;
  /**
   * Enter the full YouTube video URL (e.g., https://www.youtube.com/watch?v=VIDEO_ID)
   */
  videoUrl: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'videoSectionBlock';
}
/**
 * Manage student records, enrollment, and academic information
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "students".
 */
export interface Student {
  id: number;
  fullName: string;
  /**
   * Unique identifier for the student
   */
  studentId: string;
  dateOfBirth: string;
  gender: 'male' | 'female';
  bloodType?: ('A' | 'B' | 'AB' | 'O') | null;
  /**
   * Upload student photo (passport size recommended)
   */
  photo?: (number | null) | Media;
  email?: string | null;
  phone?: string | null;
  address: string;
  city?: string | null;
  postalCode?: string | null;
  parentName: string;
  parentPhone: string;
  parentEmail?: string | null;
  parentOccupation?: string | null;
  class: number | Class;
  enrollmentDate: string;
  previousSchool?: string | null;
  /**
   * Current enrollment status
   */
  status: 'active' | 'inactive' | 'graduated' | 'transferred';
  /**
   * Any additional information about the student
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage classes, grades, and classroom assignments
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classes".
 */
export interface Class {
  id: number;
  /**
   * e.g., Class 10A, Grade 7B
   */
  className: string;
  grade:
    | 'grade_1'
    | 'grade_2'
    | 'grade_3'
    | 'grade_4'
    | 'grade_5'
    | 'grade_6'
    | 'grade_7'
    | 'grade_8'
    | 'grade_9'
    | 'grade_10'
    | 'grade_11'
    | 'grade_12';
  /**
   * e.g., 2024/2025
   */
  academicYear: string;
  /**
   * e.g., A, B, C
   */
  section?: string | null;
  /**
   * Primary teacher responsible for this class
   */
  classTeacher: number | Teacher;
  /**
   * Additional teachers assigned to this class
   */
  assistantTeachers?: (number | Teacher)[] | null;
  /**
   * Maximum number of students
   */
  capacity: number;
  /**
   * Current number of enrolled students
   */
  currentEnrollment?: number | null;
  /**
   * Physical location of the class
   */
  classroom?: string | null;
  schedule?:
    | {
        day: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday';
        /**
         * e.g., 08:00
         */
        startTime: string;
        /**
         * e.g., 14:00
         */
        endTime: string;
        id?: string | null;
      }[]
    | null;
  subjects?:
    | {
        subjectName: string;
        teacher?: (number | null) | Teacher;
        id?: string | null;
      }[]
    | null;
  /**
   * Current status of the class
   */
  status: 'active' | 'completed' | 'cancelled';
  /**
   * Additional information about the class
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage teacher profiles, subjects, and employment information
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teachers".
 */
export interface Teacher {
  id: number;
  fullName: string;
  /**
   * Unique identifier for the teacher
   */
  employeeId: string;
  /**
   * Upload teacher photo
   */
  photo?: (number | null) | Media;
  dateOfBirth: string;
  gender: 'male' | 'female';
  email: string;
  phone: string;
  address: string;
  city?: string | null;
  postalCode?: string | null;
  /**
   * Main subject taught by the teacher
   */
  subject: string;
  additionalSubjects?:
    | {
        subjectName?: string | null;
        id?: string | null;
      }[]
    | null;
  qualification: 'high_school' | 'associate' | 'bachelor' | 'master' | 'doctorate';
  /**
   * List any teaching certifications or licenses
   */
  certifications?: string | null;
  joinDate: string;
  /**
   * Total years of teaching experience
   */
  yearsOfExperience?: number | null;
  employmentType: 'full_time' | 'part_time' | 'contract';
  /**
   * Current employment status
   */
  status: 'active' | 'on_leave' | 'resigned' | 'retired';
  /**
   * Classes currently taught by this teacher
   */
  assignedClasses?: (number | Class)[] | null;
  /**
   * Brief biography or introduction
   */
  bio?: string | null;
  /**
   * Any additional information about the teacher
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage class schedules, exams, and school events
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedules".
 */
export interface Schedule {
  id: number;
  /**
   * e.g., Mathematics Exam, Sports Day, Parent-Teacher Meeting
   */
  title: string;
  type: 'regular_class' | 'exam' | 'quiz' | 'school_event' | 'holiday' | 'meeting' | 'extra_curricular' | 'other';
  date: string;
  /**
   * For multi-day events
   */
  endDate?: string | null;
  /**
   * e.g., 09:00
   */
  startTime: string;
  /**
   * e.g., 11:00
   */
  endTime: string;
  /**
   * Leave empty for school-wide events
   */
  class?: (number | null) | Class;
  /**
   * Teacher responsible for this schedule
   */
  teacher?: (number | null) | Teacher;
  /**
   * Applicable for classes and exams
   */
  subject?: string | null;
  /**
   * Where the event will take place
   */
  location?: string | null;
  /**
   * Additional details about the schedule
   */
  description?: string | null;
  isRecurring?: boolean | null;
  recurringPattern?: ('daily' | 'weekly' | 'monthly') | null;
  status: 'scheduled' | 'in_progress' | 'completed' | 'cancelled' | 'postponed';
  /**
   * Send notification to parents about this schedule
   */
  notifyParents?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage school announcements, news, and important notices
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: number;
  title: string;
  category: 'general' | 'academic' | 'event' | 'holiday' | 'emergency' | 'achievement' | 'admission' | 'exam';
  /**
   * Urgent announcements will be highlighted
   */
  priority: 'low' | 'normal' | 'high' | 'urgent';
  /**
   * Optional image for the announcement
   */
  featuredImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  publishDate: string;
  /**
   * Announcement will be hidden after this date
   */
  expiryDate?: string | null;
  /**
   * Who should see this announcement
   */
  targetAudience: ('all' | 'students' | 'parents' | 'teachers' | 'staff')[];
  /**
   * Leave empty to show to all classes
   */
  specificClasses?: (number | Class)[] | null;
  attachments?:
    | {
        file: number | Media;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Pinned announcements appear at the top
   */
  isPinned?: boolean | null;
  /**
   * Send email to target audience
   */
  sendNotification?: boolean | null;
  status: 'draft' | 'published' | 'archived';
  author?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage school photos, videos, and event galleries
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  /**
   * e.g., Annual Sports Day 2024, Science Fair
   */
  title: string;
  category:
    | 'events'
    | 'academic'
    | 'sports'
    | 'cultural'
    | 'celebrations'
    | 'field_trips'
    | 'competitions'
    | 'graduation'
    | 'infrastructure'
    | 'other';
  /**
   * Date when the event took place
   */
  eventDate: string;
  /**
   * Brief description of the event or gallery
   */
  description?: string | null;
  /**
   * Main image representing this gallery
   */
  coverImage: number | Media;
  /**
   * Add photos and videos to this gallery
   */
  mediaItems: {
    mediaType: 'image' | 'video';
    media?: (number | null) | Media;
    /**
     * YouTube, Vimeo, or other video URL
     */
    videoUrl?: string | null;
    caption?: string | null;
    photographer?: string | null;
    id?: string | null;
  }[];
  /**
   * Classes involved in this event
   */
  relatedClasses?: (number | Class)[] | null;
  /**
   * Add tags for better searchability
   */
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Show this gallery on the homepage
   */
  featured?: boolean | null;
  /**
   * Number of times this gallery has been viewed
   */
  viewCount?: number | null;
  status: 'draft' | 'published' | 'archived';
  uploadedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'students';
        value: number | Student;
      } | null)
    | ({
        relationTo: 'teachers';
        value: number | Teacher;
      } | null)
    | ({
        relationTo: 'classes';
        value: number | Class;
      } | null)
    | ({
        relationTo: 'schedules';
        value: number | Schedule;
      } | null)
    | ({
        relationTo: 'announcements';
        value: number | Announcement;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-jobs';
        value: number | PayloadJob;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        title?: T;
        highImpactMedia?:
          | T
          | {
              image?: T;
              id?: T;
            };
        mediumImpactMedia?: T;
      };
  layout?:
    | T
    | {
        aboutSection?: T | AboutSectionSelect<T>;
        specialities?: T | SpecialitiesBlockSelect<T>;
        newsCarousel?: T | NewsCarouselSelect<T>;
        contactAndFAQ?: T | ContactAndFAQSelect<T>;
        contactBlock?: T | ContactBlockSelect<T>;
        galleryBlock?: T | GalleryBlockSelect<T>;
        imageGalleryBlock?: T | ImageGalleryBlockSelect<T>;
        mapBlock?: T | MapBlockSelect<T>;
        infoRegisterBlock?: T | InfoRegisterBlockSelect<T>;
        tentangBlock?: T | TentangBlockSelect<T>;
        'video-gallery'?: T | VideoGallerySelect<T>;
        videoSectionBlock?: T | VideoSectionBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutSection_select".
 */
export interface AboutSectionSelect<T extends boolean = true> {
  leftImage?: T;
  subtitle?: T;
  title?: T;
  description?: T;
  buttonText?: T;
  buttonLink?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpecialitiesBlock_select".
 */
export interface SpecialitiesBlockSelect<T extends boolean = true> {
  sectionTitle?: T;
  items?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        color?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsCarousel_select".
 */
export interface NewsCarouselSelect<T extends boolean = true> {
  subtitle?: T;
  heading?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactAndFAQ_select".
 */
export interface ContactAndFAQSelect<T extends boolean = true> {
  formSubtitle?: T;
  formTitle?: T;
  fullNameLabel?: T;
  phoneLabel?: T;
  emailLabel?: T;
  messageLabel?: T;
  submitLabel?: T;
  faqSubtitle?: T;
  faqTitle?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock_select".
 */
export interface ContactBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  formTitle?: T;
  showAddress?: T;
  showPhone?: T;
  showEmail?: T;
  address?: T;
  phoneNumber?: T;
  emailAddress?: T;
  formPlaceholders?:
    | T
    | {
        name?: T;
        email?: T;
        message?: T;
        submit?: T;
      };
  socialMedia?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock_select".
 */
export interface GalleryBlockSelect<T extends boolean = true> {
  subtitle?: T;
  title?: T;
  items?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageGalleryBlock_select".
 */
export interface ImageGalleryBlockSelect<T extends boolean = true> {
  images?:
    | T
    | {
        image?: T;
        title?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MapBlock_select".
 */
export interface MapBlockSelect<T extends boolean = true> {
  title?: T;
  latitude?: T;
  longitude?: T;
  zoom?: T;
  label?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InfoRegisterBlock_select".
 */
export interface InfoRegisterBlockSelect<T extends boolean = true> {
  title?: T;
  buttonHref?: T;
  buttonLabel?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TentangBlock_select".
 */
export interface TentangBlockSelect<T extends boolean = true> {
  left?:
    | T
    | {
        image?: T;
        content?: T;
      };
  right?:
    | T
    | {
        widgets?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    label?: T;
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          reference?: T;
                          staticPath?: T;
                          url?: T;
                        };
                    image?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoGallery_select".
 */
export interface VideoGallerySelect<T extends boolean = true> {
  videos?:
    | T
    | {
        youtubeUrl?: T;
        title?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoSectionBlock_select".
 */
export interface VideoSectionBlockSelect<T extends boolean = true> {
  thumbnail?: T;
  videoUrl?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugLock?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "students_select".
 */
export interface StudentsSelect<T extends boolean = true> {
  fullName?: T;
  studentId?: T;
  dateOfBirth?: T;
  gender?: T;
  bloodType?: T;
  photo?: T;
  email?: T;
  phone?: T;
  address?: T;
  city?: T;
  postalCode?: T;
  parentName?: T;
  parentPhone?: T;
  parentEmail?: T;
  parentOccupation?: T;
  class?: T;
  enrollmentDate?: T;
  previousSchool?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teachers_select".
 */
export interface TeachersSelect<T extends boolean = true> {
  fullName?: T;
  employeeId?: T;
  photo?: T;
  dateOfBirth?: T;
  gender?: T;
  email?: T;
  phone?: T;
  address?: T;
  city?: T;
  postalCode?: T;
  subject?: T;
  additionalSubjects?:
    | T
    | {
        subjectName?: T;
        id?: T;
      };
  qualification?: T;
  certifications?: T;
  joinDate?: T;
  yearsOfExperience?: T;
  employmentType?: T;
  status?: T;
  assignedClasses?: T;
  bio?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classes_select".
 */
export interface ClassesSelect<T extends boolean = true> {
  className?: T;
  grade?: T;
  academicYear?: T;
  section?: T;
  classTeacher?: T;
  assistantTeachers?: T;
  capacity?: T;
  currentEnrollment?: T;
  classroom?: T;
  schedule?:
    | T
    | {
        day?: T;
        startTime?: T;
        endTime?: T;
        id?: T;
      };
  subjects?:
    | T
    | {
        subjectName?: T;
        teacher?: T;
        id?: T;
      };
  status?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedules_select".
 */
export interface SchedulesSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  date?: T;
  endDate?: T;
  startTime?: T;
  endTime?: T;
  class?: T;
  teacher?: T;
  subject?: T;
  location?: T;
  description?: T;
  isRecurring?: T;
  recurringPattern?: T;
  status?: T;
  notifyParents?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  priority?: T;
  featuredImage?: T;
  content?: T;
  publishDate?: T;
  expiryDate?: T;
  targetAudience?: T;
  specificClasses?: T;
  attachments?:
    | T
    | {
        file?: T;
        description?: T;
        id?: T;
      };
  isPinned?: T;
  sendNotification?: T;
  status?: T;
  author?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  title?: T;
  category?: T;
  eventDate?: T;
  description?: T;
  coverImage?: T;
  mediaItems?:
    | T
    | {
        mediaType?: T;
        media?: T;
        videoUrl?: T;
        caption?: T;
        photographer?: T;
        id?: T;
      };
  relatedClasses?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  featured?: T;
  viewCount?: T;
  status?: T;
  uploadedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          /**
           * Link ke halaman statis internal (tanpa memilih dokumen)
           */
          staticPath?: '/posts' | null;
          url?: string | null;
          label: string;
        };
        /**
         * Second level navigation items (dropdown items)
         */
        children?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: number | Page;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: number | Post;
                    } | null);
                staticPath?: '/posts' | null;
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          staticPath?: ('' | '/posts') | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  contactInfo?: {
    address?: string | null;
    phone?: string | null;
    email?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configure school profile, contact information, and general settings
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "school-settings".
 */
export interface SchoolSetting {
  id: number;
  schoolName: string;
  /**
   * Upload school logo (recommended: square, min 200x200px)
   */
  schoolLogo: number | Media;
  /**
   * Short motto or tagline
   */
  tagline?: string | null;
  /**
   * Brief description of the school
   */
  aboutSchool?: string | null;
  establishedYear?: number | null;
  affiliationNumber?: string | null;
  principalName?: string | null;
  principalMessage?: string | null;
  principalPhoto?: (number | null) | Media;
  address: string;
  city: string;
  state?: string | null;
  postalCode: string;
  country: string;
  phoneNumber: string;
  alternatePhone?: string | null;
  email: string;
  website?: string | null;
  /**
   * Embed URL from Google Maps
   */
  mapLocation?: string | null;
  facebook?: string | null;
  twitter?: string | null;
  instagram?: string | null;
  youtube?: string | null;
  linkedin?: string | null;
  /**
   * e.g., 2024/2025
   */
  currentAcademicYear: string;
  academicYearStart?: string | null;
  academicYearEnd?: string | null;
  workingDays: ('monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday')[];
  /**
   * e.g., 08:00
   */
  schoolStartTime?: string | null;
  /**
   * e.g., 14:00
   */
  schoolEndTime?: string | null;
  /**
   * e.g., Asia/Jakarta, America/New_York
   */
  timezone?: string | null;
  dateFormat?: ('DD/MM/YYYY' | 'MM/DD/YYYY' | 'YYYY-MM-DD') | null;
  language?: ('en' | 'id') | null;
  /**
   * Enable to show maintenance message on frontend
   */
  maintenanceMode?: boolean | null;
  maintenanceMessage?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              staticPath?: T;
              url?: T;
              label?: T;
            };
        children?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    staticPath?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              staticPath?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  contactInfo?:
    | T
    | {
        address?: T;
        phone?: T;
        email?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "school-settings_select".
 */
export interface SchoolSettingsSelect<T extends boolean = true> {
  schoolName?: T;
  schoolLogo?: T;
  tagline?: T;
  aboutSchool?: T;
  establishedYear?: T;
  affiliationNumber?: T;
  principalName?: T;
  principalMessage?: T;
  principalPhoto?: T;
  address?: T;
  city?: T;
  state?: T;
  postalCode?: T;
  country?: T;
  phoneNumber?: T;
  alternatePhone?: T;
  email?: T;
  website?: T;
  mapLocation?: T;
  facebook?: T;
  twitter?: T;
  instagram?: T;
  youtube?: T;
  linkedin?: T;
  currentAcademicYear?: T;
  academicYearStart?: T;
  academicYearEnd?: T;
  workingDays?: T;
  schoolStartTime?: T;
  schoolEndTime?: T;
  timezone?: T;
  dateFormat?: T;
  language?: T;
  maintenanceMode?: T;
  maintenanceMessage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}